### ISSUE TITLE
Rebase大学 x 1circle 开发者活动 | Algorand的共识算法与应用开发

### ISSUE THREAD

**Issue by Xiu88** [rebase-network/event-pool#1]
![954B3EDF-E396-4648-891B-64D8730D6F0E](https://user-images.githubusercontent.com/98024365/150127965-0d93829f-42d0-4abf-ad35-8a7ab2a366ae.jpeg)

1月20日晚9点，1circle中文社区 与 Rebase大学 将共同举办开发者会议——Algorand 的共识算法与应用开发，本次活动邀请到 Algorand基金会 的亚太区生态开发负责人 haichao，将会为各位开发者介绍 Algorand 的共识算法和应用开发情况，包括开发环境，语言，基金会项目等一系列支持开发者的活动情况介绍。

**Algorand 共识算法**

Algorand 基于的共识协议是PPoS，纯粹的权益证明，有与其他 Layer1 公链不同的特性：

- 系统不需要惩罚或没收用户的 stake 来防止作恶。因为通过严格的数学证明，即使用户想要作恶，他成功的概率也是非常小的，也不会对系统造成伤害，降低了作恶动机。

- 系统不要求用户锁定 token，拥有的所有 stake 都可以立即花出去。每个用户都可以随时注册、参与。

- 安全性假设使诚实的用户掌握 token 和 stake ，因此系统就会是安全的。类似于工作量证明中，整个系统中的算力掌握在诚实的用户手中。

- 所有的 token 都有同样的 voting power，所有的用户都可以选择参与共识协议。

**Algorand 开发环境与轻松完成dApp构建**

Algorand 旨在让每个人都能使用区块链。Algorand 生态代表了一个多用途、多功能的网络，支持所有类型的数字资产、智能合约和区块链驱动的应用。

开发人员可以使用 Algorand 标准资产 (ASA) 框架创建新资产，例如实用通证、非同质化通证 (NFT) 或对现实世界的资产进行通证化。他们能够在几分钟内在 Algorand 的 Layer -1 第一层上构建资产，享受 Layer -1 第一层的强大功能，如真正的去中心化、高安全性、高吞吐量和高速等。

Algorand 允许开发人员使用自己熟悉的编程语言来构建资产。Algorand 支持 Java、JavaScript（node.js 和浏览器）、Go 和 Python SDK、REST API，以及多种社区 SDK，例如 rust、swift、PHP、dart、C# 等。在 Algorand 链上构建智能合约也是如此。Algorand 提供了新一代智能合约框架，使企业和开发人员可以构建更复杂、更灵活、更快捷的应用，同时精简流程。

**Algorand 开发者激励**

**Algorand 有总量超过 10亿 美金的生态Grant、开发者、黑客松、加速器等为开发者定制的激励，参与活动了解更多内容！**

参加讲座还将获得我们活动限定 NFT 徽章 ——

注意：领取徽章需要下载 Algorand 钱包并添加资产，可以参考教程：
https://youtube.com/playlist?list=PL1Joo_PXkCg0j_TDj8vo0Q7u5DhVWQq7J

![24F9D159-B934-44F9-ADC3-01372A56B8A2](https://user-images.githubusercontent.com/98024365/150128250-32f4969f-fc22-4df3-b080-5ce13952aa55.jpeg)

![C6ADD217-8B2F-4309-8C45-B935F7F73DD0](https://user-images.githubusercontent.com/98024365/150128311-9c4cda8a-3ce7-4b19-b660-09a8f10b09e9.jpeg)

**Comment by luckyyang** [comment]
分享资料:
https://docs.google.com/presentation/d/1puT8SNim0zwm1UNutDU8C5zvGvTjZXM5XdYkM9Uw1HY/edit#slide=id.g7e7f855484_1_108

https://docs.google.com/presentation/d/1WlU6Vhcz19hziMhWvE3udwP9XyXuT0rJXe7aT7kTUJY/edit#slide=id.gdd4491ae89_2_152

https://docs.google.com/presentation/d/1fDRsiEgR6Q-1COg6ddGVHZ7dBD9i95egdiKexvSj_Yc/edit#slide=id.p6
